# #3. 비동기 코드 테스트
## callback
### fn.js
```javascript
const fn = {
  getName: (callback) => {
    const name = 'seungha';
    setTimeout
    (() => {
      callback(name);
    }, 3000);
  }
} 
``` 
- 3초 후에 name을 callback 함수의 인수로 넘겨주는 getName() 함수이다.

### fn.test.js
```javascript
test('3초 후에 받아온 이름은 seungha입니다.', () => {
  function callback(name) {
    expect(name).toBe('seungha'); 
  }
  fn.getName(callback); // passed
})

test('3초 후에 받아온 이름은 seungha입니다.', () => {
  function callback(name) {
    expect(name).toBe('seunghee');
  }
  fn.getName(callback); // passed
})
```
- 3초 후에 name을 반환해야 하지만 테스트코드는 1ms 만에 종료된다. 
- name이 seungha가 아닌 seunghee여도 테스트가 통과한다.

### 왜?
- jest는 test()의 콜백함수가 끝에 도달하면 실행이 종료된다. (비동기)
- setTimeout을 기다리지 않고 실행이 종료된다. 
- test()에 done을 전달해주면 된다.

### fn.test.js
```javascript
test('3초 후에 받아온 이름은 seungha입니다.', (done) => {
  function callback(name) {
    expect(name).toBe('seungha');
    done();
  }
  fn.getName(callback); // passed
})

test('3초 후에 받아온 이름은 seungha입니다.', (done) => {
  function callback(name) {
    expect(name).toBe('seungha');
    done();
  }
  fn.getName(callback); // failed
})
```
- 위 두 테스트코드는 3초가 지난 뒤에 결과를 확인할 수 있었다.
- done() 이 호출되기 전까지 jest는 테스트를 끝내지 않고 기다린다.

```javascript
test('3초 후에 받아온 이름은 seungha입니다.', (done) => {
  function callback(name) {
    expect(name).toBe('seungha');
    // done();
  }
  fn.getName(callback) // timeout
})
```
- done()을 호출하지 않으면 timeout으로 테스트를 실패하게 된다.

### fn.js
```javascript
const fn = {
  getName: (callback) => {
    const name = 'seungha';
    setTimeout
    (() => {
      // callback(name);
      throw new Error('sever error');
    }, 3000);
  }
}
```
- callback에서 3초 뒤 에러를 던지게 한다.

### fn.test.js 
```javascript
test('3초 후에 받아온 이름은 seungha입니다.', (done) => {
  function callback(name) {
    try {
      expect(name).toBe('seungha');
      done();
    } catch (err) {
      done(err);
    }
  }
  fn.getName(callback); // server error
})
```
- api 에러를 감지하고 싶다면 try catch문으로 감싸준다. 

## Promise
### fn.js
```javascript
const fn = {
  getAge: () => {
    const age = 30;
    return new Promise((res, rej) => {
      setTimeout(() => {
        res(age);
      }, 3000);
    })
  } 
}
```
- Promise를 return하면 jest는 resolve 될 때 까지 기다려준다.

### fn.test.js
```javascript
test('3초 후에 받아온 나이는 30살 입니다.', () => {
  fn.getAge().then(age => {
    expect(age).toBe(31); // passed
  })
})
```
- Promise를 사용할 때는 return을 해주어야 한다.

```javascript
test('3초 후에 받아온 나이는 30살 입니다.', () => {
  return fn.getAge().then(age => {
    expect(age).toBe(31); // failed
  })
})
```
- 간단하게 사용하려면 resolves() matcher를 사용한다.

### fn.test.js
```javascript
test('3초 후에 받아온 나이는 30살 입니다.', () => {
  return expect(fn.getAge()).resolves.toBe(30); // passed
}) 
```
- reject 상황을 테스트 하고 싶을 때는 rejects() matcher를 사용한다.

## async/await
### fn.test.js
```javascript
test('3초 후에 받아온 나이는 30살 입니다.', async () => {
  const age = await fn.getAge();
  expect(age).toBe(30);
})
```
- resolves() matcher를 사용할 수도 있다.
```javascript
test('3초 후에 받아온 나이는 30살 입니다.', async () => {
  await expect(fn.getAge()).resolves.toBe(30);
})
```